version: "3.8"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - 5432:5432

  user_app:
    build:
      context: ./
      dockerfile: dockerfile

    environment:
      - DATABASE_URL=postgresql://postgres:mysecretpassword@postgres:5432/postgresql

    ports:
      - 3000:3000

    depends_on:
      - postgres
